# global.$ = global.jQuery = $ = require "jquery"
#
# require "bootstrap-sass/assets/javascripts/bootstrap/transition"
# require "bootstrap-sass/assets/javascripts/bootstrap/tab"
# require "bootstrap-sass/assets/javascripts/bootstrap/dropdown"
# require "bootstrap-sass/assets/javascripts/bootstrap/collapse"
# require "bootstrap-sass/assets/javascripts/bootstrap/modal"
# require "bootstrap-sass/assets/javascripts/bootstrap/tooltip"
# require "bootstrap-sass/assets/javascripts/bootstrap/popover"
# require "bootstrap-validator"
